trigger:

  none

variables:
  buildAgentPool: 'vb6buildhost'
  gitEmail: 'buildpipeline@robpitcher.com'
  gitUserName: 'buildpipeline'
  buildUserProfile: 'C:\Windows\ServiceProfiles\NetworkService'
  pvtKeyFile: 'id_ed25519'
  pubKeyFile: 'id_ed25519.pub'

pool:
  name: $(buildAgentPool)

steps:

# Using this task instead of clean:true on the checkout step because clean:true does not purge the .git directory
# Also clearing .gitconfig just in case
- task: PowerShell@2
  displayName: Clean Up / Prep Git
  inputs:
    targetType: inline
    workingDirectory: $(System.DefaultWorkingDirectory)
    script: |
      Get-ChildItem -Force | Remove-Item -Recurse -Confirm:$false -Force -ErrorAction silentlycontinue
      Remove-Item -Path "${env:buildUserProfile}\.gitconfig" -Force -Confirm:$false -ErrorAction silentlycontinue
      Remove-Item -Path "${env:buildUserProfile}\.ssh\known_hosts*" -Force -Confirm:$false -ErrorAction silentlycontinue

- checkout: self
  persistCredentials: true
  fetchDepth: 0

# Download the private key to the buildhost from secure file library
- task: DownloadSecureFile@1
  name: pvtkeyName
  inputs:
    secureFile: $(pvtKeyFile)

# Download the public key to the buildhost from secure file library
- task: DownloadSecureFile@1
  name: pubKeyName
  inputs:
    secureFile: $(pubKeyFile)

- script: |
   copy $(pvtKeyName.secureFilePath) "%buildUserProfile%\.ssh" /Y
   copy $(pubKeyName.secureFilePath) "%buildUserProfile%\.ssh" /Y
   git config --global --add url."git@github.com:".insteadOf "https://github.com/"
   git config --global user.email $(gitEmail) & git config --global user.name $(gitUserName)
   ssh-agent
   ssh-add "%buildUserProfile%\.ssh\id_ed25519"
   ssh-keyscan -t rsa github.com >> "%buildUserProfile%\.ssh\known_hosts"
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: Configure git & SSH key

- script: |
   git checkout -b main
   git pull origin main
  displayName: Checkout and pull repo