trigger:

  none

variables:
  buildAgentPool: 'vb6buildhost'
  gitEmail: 'buildpipeline@robpitcher.com'
  gitUserName: 'buildpipeline'

pool:
  name: $(buildAgentPool)

steps:

# Using this task instead of clean: true on the checkout step because clean: true does not purge the .git directory
# Also clearing .gitconfig to make this pipeline idempotent
- task: PowerShell@2
  displayName: Clean up any existing local repos
  inputs:
    targetType: inline
    workingDirectory: $(System.DefaultWorkingDirectory)
    script: |
      Get-ChildItem -Force | Remove-Item -Recurse -Confirm:$false -Force -ErrorAction silentlycontinue
      Remove-Item -Path "C:\Windows\ServiceProfiles\NetworkService\.gitconfig" -Force -Confirm:$false -ErrorAction silentlycontinue
# Should we also clear out known hosts?: Remove-Item -Path C:\Windows\ServiceProfiles\NetworkService\.ssh\known_hosts -Force -Confirm:$false -ErrorAction silentlycontinue

- checkout: self
  persistCredentials: true
  fetchDepth: 0

- script: |
   git config --global --add url."git@github.com:".insteadOf "https://github.com/"
   git config --global user.email $(gitEmail) & git config --global user.name $(gitUserName)
   ssh-agent
   ssh-add C:\Windows\ServiceProfiles\NetworkService\.ssh\id_ed25519
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: Configure git & SSH key
# ssh-keyscan -t rsa github.com >> C:\Windows\ServiceProfiles\NetworkService\.ssh\known_hosts

- script: |
   git checkout -b main
   git pull origin main
  displayName: Checkout and pull repo