trigger:

  none

variables:
  buildAgentPool: 'vb6buildhost'
  gitEmail: 'buildpipeline@robpitcher.com'
  gitUserName: 'buildpipeline'

pool:
  name: $(buildAgentPool)

steps:

# Using this task instead of clean: true on the checkout step because clean: true does not purge the .git directory
- task: PowerShell@2
  displayName: Clean up any existing local repos
  inputs:
    targetType: inline
    workingDirectory: $(System.DefaultWorkingDirectory)
    script: |
      Get-ChildItem -Force | Remove-Item -Recurse -Confirm:$false -Force

- checkout: self
  persistCredentials: true
  fetchDepth: 0

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'RPLabs-Management-Dev(c333cca8-a598-4d98-bbbd-a601792ba259)'
    KeyVaultName: 'vb6kv'
    SecretsFilter: '*'
    RunAsPreJob: false

- script: |
   git config --global --add url."git@github.com:".insteadOf "https://github.com/"
   git config --global user.email $(gitEmail) & git config --global user.name $(gitUserName)
   ssh-agent
   ssh-add C:\Windows\ServiceProfiles\NetworkService\.ssh\id_ed25519
   ssh-keyscan -t rsa github.com >> C:\Windows\ServiceProfiles\NetworkService\.ssh\known_hosts
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: Configure git & SSH key

- script: |
   git checkout -b main
   git pull origin main
  displayName: Checkout and pull repo

- task: CmdLine@2
  displayName: Get ssh keys from kv
  inputs:
    script: | 
      echo $(sshprivatekey) > id_ed25519
      echo $(sshpubkey) > id_ed25519.pub