trigger:
  branches:
    include:
    - main
  paths:
    include:
    - scripts/thing1.ps1

variables:
  buildAgentPool: 'vb6buildhost'
  gitEmail: 'buildpipeline@robpitcher.com'
  gitUserName: 'buildpipeline'
  repoPath: 'C:\agents\_work\1\s'
  scriptPath: 'scripts\thing1.ps1'
  
pool:
  name: $(buildAgentPool)

steps:

- checkout: none

- task: InstallSSHKey@0
  displayName: Testing ssh key install
  inputs:
    # addEntryToConfig: true
    # configHostAlias: 'vm02-ssh'
    knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCOTsnMrWbot00RsVV1QyH/C7TaoC8pcj/OO2X0xuBZ37FFbJ+PL5FCUM42LWuXwFyDp9UEigTwuZvKkexSakCJrI0D0+w7UDPwPdOfzlj/9EwPDAsj5Iw/iB2wlor0QmKm5pRsYVk9y4HOVBmChaMy62WrGAJaKHtnV9j5TjtHDD1XQUdsoFP7YlwrwDxdrvpmroQ1JLAtTwJYQeyU/eigt5JKd4ALTA5wuWkFQleJkX041mjYNIIwwRthvm9jyPHUL3BCOZRCActbFECRrG4gMfgDrQ16KdWdnpf/A1fTgyhFuGUMO82YUJUBCyrhizijCtQSZfBgSrCCVVqgMcCe+OWAzeWpsGvpslGpSoA9AbtSC4TCp/Wft4mXGdqG1y7t9YHfmhvx0Ho0mUiL3QEKgGEazZwL1RvxBnyjW8BTy0zMdA/LxDPYDBKxih/DOfEJiS5iMOYx0Rmzc337DCbdadSfRWwUwaIetdXTsaVHQgQMB95m5TUOu/htz3nAUc= rob@vm03'
    #sshPassphrase: # Optional
    sshKeySecureFile: id_rsa

- task: PowerShell@2
  displayName: hol up
  inputs:
    targetType: inline
    script: |
      start-sleep -seconds 120

- script: |
   git checkout main
   git pull origin main 
  workingDirectory: $(repoPath)
  displayName: Checkout and pull repo

- task: PowerShell@2
  displayName: Run update revision info script
  inputs:
    targetType: filePath
    filePath: $(repoPath)\$(scriptPath)
    workingDirectory: $(repoPath)

- script: |
    git add -A
    git commit -m "update revision info [skip ci]"
    git push --set-upstream origin main
  workingDirectory: $(repoPath)
  displayName: Commit revision info output