trigger:
  branches:
    include:
    - main
  paths:
    include:
    - scripts/thing1.ps1

variables:
  buildAgentPool: 'vb6buildhost'
  gitEmail: 'buildpipeline@robpitcher.com'
  gitUserName: 'buildpipeline'
  repoPath: 'C:\agent\_work\1\s'
  scriptPath: 'scripts\thing1.ps1'
  
pool:
  name: $(buildAgentPool)

steps:

- checkout: none
  persistCredentials: true

- task: PowerShell@2
  displayName: Echo user profile
  inputs:
    targetType: inline
    script:
      echo $env:USERPROFILE

- script: |
   git config --global user.email $(gitEmail) & git config --global user.name $(gitUserName)
   ssh-agent
   ssh-add ~/.ssh/id_ed25519
  workingDirectory: $(repoPath)
  displayName: Set git config

- script: |
   git checkout main
   git pull origin main
  workingDirectory: $(repoPath)
  displayName: Checkout and pull repo

- task: PowerShell@2
  displayName: Run update revision info script
  inputs:
    targetType: filePath
    filePath: $(repoPath)\$(scriptPath)
    workingDirectory: $(repoPath)

- script: |
    git add -A
    git commit -m "update revision info [skip ci]"
    git push --set-upstream origin main
  workingDirectory: $(repoPath)
  displayName: Commit revision info output