trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - scripts/thing1.ps1

variables:
  buildAgentPool: 'vb6buildhost'
  gitEmail: 'buildpipeline@robpitcher.com'
  gitUserName: 'buildpipeline'
  repoPath: 'C:\agents\_work\1\s'
  scriptPath: 'pipelines\fileVersioningUpdate.ps1'
  rowKey: 'thing1'
  
pool:
  name: $(buildAgentPool)

steps:

- checkout: none

- script: |
   git checkout $(Build.SourceBranchName)
   git pull origin $(Build.SourceBranchName) 
  workingDirectory: $(repoPath)
  displayName: Checkout and pull repo

- task: PowerShell@2
  displayName: Run update revision info script
  inputs:
    targetType: filePath
    filePath: $(repoPath)\$(scriptPath)
    workingDirectory: $(repoPath)

- script: |
    git add -A
    git commit -m "update revision info [skip ci]"
    git push --set-upstream origin $(Build.SourceBranchName)
  workingDirectory: $(repoPath)
  displayName: Commit revision info output