trigger:
  branches:
    include:
    - main
  paths:
    include:
    - scripts/thing1.ps1

variables:
  buildAgentPool: 'vb6buildhost'
  gitEmail: 'buildpipeline@robpitcher.com'
  gitUserName: 'buildpipeline'
  repoPath: 'C:\agents\_work\1\s'
  scriptPath: 'scripts\thing1.ps1'
  
pool:
  name: $(buildAgentPool)

steps:

- checkout: none

- script: |
   git checkout main
  workingDirectory: $(repoPath)
  displayName: Checkout and pull repo
  # git pull origin main Took this out

- task: PowerShell@2
  displayName: Run update revision info script
  inputs:
    targetType: filePath
    filePath: $(repoPath)\$(scriptPath)
    workingDirectory: $(repoPath)

- script: |
    git add -A
    git commit -m "update revision info [skip ci]"
    git push --set-upstream origin main
  workingDirectory: $(repoPath)
  displayName: Commit revision info output